*** Variables ***
${HOT_URL}                https://hotcorphml.globalhitss.com.br/new_demand_management/edit/
${HOT_URL_FRAGMENT}       hotcorphml.globalhitss.com.br
${BPWEB_URL}              https://bpwebhml.globalhitss.com.br/businessplan/home
${BPWEB_URL_FRAGMENT}     bpwebhml.globalhitss.com.br
${BHUB_URL}               https://bhubhml.globalhitss.com.br/
${BHUB_URL_FRAGMENT}      bhubhml.globalhitss.com.br

${BROWSER}                chromium
${HEADLESS}               ${False}
${TIMEOUT}                20s
